### ISSUE TITLE
Array out of bounds crash

### ISSUE THREAD

**Issue by Aaron995** [Fulmineo64/Guild#15]
**Modloader**
Did you experience the issue while playing on Fabric or on Forge?
Fabric

**Describe the bug**
Have all 8 professions, open the profession window and you crash due to array out of bounds. "java.lang.ArrayIndexOutOfBoundsException: Index 7 out of bounds for length 7"

**To Reproduce**
1. Get all 8 professions
2. Press J 
3. Crash

**Expected behavior**
Not to crash and see my profession window

**Screenshots**

**Additional context**
```
[21:55:56] [Render thread/FATAL]: Error executing task on Client
java.lang.ArrayIndexOutOfBoundsException: Index 7 out of bounds for length 7
	at dev.fulmineo.guild.screen.QuestsScreen.method_25426(QuestsScreen.java:67) ~[guild-fabric-0.3.6.jar:?]
	at net.minecraft.class_437.method_25423(class_437.java:388) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1507(class_310.java:989) ~[client-intermediary.jar:?]
	at net.fabricmc.fabric.impl.screenhandler.client.ClientNetworking.openScreen(ClientNetworking.java:86) ~[fabric-screen-handler-api-v1-1.1+3ac43d9565-dd22ab73dd9bc044.jar:?]
	at net.fabricmc.fabric.impl.screenhandler.client.ClientNetworking.lambda$onInitializeClient$0(ClientNetworking.java:54) ~[fabric-screen-handler-api-v1-1.1+3ac43d9565-dd22ab73dd9bc044.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:151) [client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:125) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:110) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1080) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:733) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:238) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.12.jar:?]
	```

**Comment by Fulmineo64** [comment]
Hi Aaron, 
you should be able to obtain only up to 7 professions, 
how did you manage to get 8?

Also can you tell me which version of The Guild are you using?
Thank you!

**Comment by Aaron995** [comment]
Hey, 

The villagers trade 8 total professions and I was able to assign myself 8 professions through just learning the 8th one. 
Guild version: 0.3.6

Server I played on updated version and now it's fixed :)
